#!/usr/bin/env python3
"""Generate docs/CHECKS.md: one row per registry check, from controls/registry.json plus controls/registry.d/*.json.

Overlays are applied in file-name order and a later entry replaces the base entry with the same id, exactly as
the binary loads them. Re-run after changing the registry and commit the result:

    scripts/checks-table.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTROLS = ROOT / "controls"
OUT = ROOT / "docs" / "CHECKS.md"

SEVERITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Info": 4}


def load_checks() -> dict[str, dict]:
    files = [CONTROLS / "registry.json"] + sorted((CONTROLS / "registry.d").glob("*.json"))
    checks: dict[str, dict] = {}
    for f in files:
        for c in json.loads(f.read_text())["checks"]:
            checks[c["checkId"]] = c
    return checks


def framework_ref(check: dict, key: str) -> str:
    return (check.get("frameworks") or {}).get(key, {}).get("controlId", "").replace(";", ", ")


def severity(check: dict) -> str:
    return (check.get("impactRating") or {}).get("severity") or "Medium (default)"


def main() -> None:
    checks = load_checks()
    overrides = json.loads((CONTROLS / "risk-severity.json").read_text())["checks"]
    rows = sorted(checks.values(), key=lambda c: c["checkId"])
    automated = sum(1 for c in rows if c.get("hasAutomatedCheck"))

    lines = [
        "# Check catalogue",
        "",
        "Generated by `scripts/checks-table.py` from `controls/registry.json` and `controls/registry.d/*.json`; do not edit by hand.",
        "",
        f"{len(rows)} checks, {automated} automated, {len(rows) - automated} manual or not yet implemented.",
        "",
        "Severity is the registry `impactRating.severity`; a value in `controls/risk-severity.json` overrides it and is shown as `registry -> override`.",
        "",
        "| Check id | Name | Category | Severity | Automated | CIS M365 v7 | NIST CSF 2.0 |",
        "|---|---|---|---|---|---|---|",
    ]
    for c in rows:
        sev = severity(c)
        if c["checkId"] in overrides and overrides[c["checkId"]] != sev:
            sev = f"{sev} -> {overrides[c['checkId']]}"
        lines.append(
            "| {id} | {name} | {cat} | {sev} | {auto} | {cis} | {csf} |".format(
                id=c["checkId"],
                name=c["name"].replace("|", "\\|"),
                cat=c.get("category", ""),
                sev=sev,
                auto="yes" if c.get("hasAutomatedCheck") else "no",
                cis=framework_ref(c, "cis-m365-v7"),
                csf=framework_ref(c, "nist-csf"),
            )
        )
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} checks")


if __name__ == "__main__":
    main()
