//! Gateway to Microsoft APIs outside Graph and Exchange, through Junction
//! (<https://github.com/jusso-dev/junction>): Azure Resource Manager, Resource Graph, Defender for
//! Cloud, Sentinel, Defender for Endpoint and Power Platform.
//!
//! Junction turns Microsoft's published API specifications into a catalogue of operations with their
//! paths, API versions, parameters and paging rules, and runs them under a read-only policy. We embed
//! the handful of operations the modules call (`controls/junction-catalog.json`, regenerated by
//! `scripts/junction-catalog.py`) so the binary stays self-contained, and hand Junction tokens acquired
//! by our own sign-in. Modules call operations by id instead of hand-writing URLs:
//!
//! ```ignore
//! let jx = JunctionGateway::new(graph)?;
//! let vaults = jx
//!     .list(Resource::AzureResourceManager, "azure.key_vault.vaults.list_by_subscription",
//!           JunctionGateway::params(&[("subscriptionId", sub)]))
//!     .await?;
//! ```

use std::time::SystemTime;

use anyhow::{Context, Result};
use junction_auth::{AccessToken, Secret, TokenMetadata};
use junction_core::RegistryManifest;
use junction_policy::{Limits, Policy};
use junction_registry::Registry;
use junction_runtime::{ExecutionContext, Executor, PageOptions};
use serde_json::{json, Value};

use crate::auth::{AuthManager, CloudEnvironment, Resource};
use crate::graph::GraphClient;

/// The embedded subset of Junction's catalogue.
const CATALOG: &str = include_str!("../controls/junction-catalog.json");

pub struct JunctionGateway {
    executor: Executor,
    auth: AuthManager,
}

impl JunctionGateway {
    pub fn new(graph: &GraphClient) -> Result<Self> {
        let manifest: RegistryManifest =
            serde_json::from_str(CATALOG).context("parsing embedded Junction catalogue")?;
        let registry = Registry::load(manifest).context("loading embedded Junction catalogue")?;
        // Read-only is Junction's default; only the volume limits are raised to assessment scale.
        let policy = Policy {
            limits: Limits {
                max_requests_per_minute: 300,
                max_pages: 200,
                max_parallel_requests: 10,
                max_batch_operations: 100,
                max_items: 50_000,
            },
            ..Policy::default()
        };
        Ok(Self {
            executor: Executor::new(registry, policy)?,
            auth: graph.auth().clone(),
        })
    }

    /// Build the `parameters` input object from path/query parameter pairs.
    pub fn params(pairs: &[(&str, &str)]) -> Value {
        let mut map = serde_json::Map::new();
        for (k, v) in pairs {
            map.insert((*k).to_string(), Value::String((*v).to_string()));
        }
        json!({ "parameters": map })
    }

    /// Run one operation and return the response body.
    pub async fn call(&self, resource: Resource, operation: &str, input: Value) -> Result<Value> {
        let input = self.with_api_version(operation, input)?;
        let (endpoint, audience) = endpoint_for(self.auth.cloud(), resource)?;
        let token = self.access_token(resource, &audience).await?;
        let context = ExecutionContext {
            tenant: self.auth.tenant_id(),
            audience: &audience,
            endpoint: &endpoint,
            token: &token,
        };
        let response = self
            .executor
            .execute(operation, input, context, None, false)
            .await
            .map_err(|e| {
                anyhow::anyhow!(
                    "{} via Junction ({}) failed: {}",
                    operation,
                    resource.display_name(),
                    e
                )
            })?;
        if response.status >= 400 {
            anyhow::bail!(
                "{} via Junction ({}) returned HTTP {}",
                operation,
                resource.display_name(),
                response.status
            );
        }
        Ok(response.body)
    }

    /// Run a list operation, following paging, and return the items.
    /// Operations without declared paging return their `value` array (or the body itself).
    pub async fn list(
        &self,
        resource: Resource,
        operation: &str,
        input: Value,
    ) -> Result<Vec<Value>> {
        let pageable = self
            .executor
            .registry()
            .resolve(operation, None, false)
            .map(|op| op.pageable.is_some() || op.query_continuation.is_some())
            .unwrap_or(false);
        if !pageable {
            let body = self.call(resource, operation, input).await?;
            return Ok(match body {
                Value::Array(items) => items,
                Value::Object(ref map) => map
                    .get("value")
                    .or_else(|| map.get("data"))
                    .and_then(|v| v.as_array())
                    .cloned()
                    .unwrap_or_else(|| vec![body.clone()]),
                other => vec![other],
            });
        }
        let input = self.with_api_version(operation, input)?;
        let (endpoint, audience) = endpoint_for(self.auth.cloud(), resource)?;
        let token = self.access_token(resource, &audience).await?;
        let context = ExecutionContext {
            tenant: self.auth.tenant_id(),
            audience: &audience,
            endpoint: &endpoint,
            token: &token,
        };
        let options = PageOptions {
            max_items: 50_000,
            max_pages: 200,
            api_version: None,
            allow_preview: false,
        };
        let result = self
            .executor
            .execute_pages(operation, input, context, options)
            .await
            .map_err(|e| {
                anyhow::anyhow!(
                    "{} via Junction ({}) failed: {}",
                    operation,
                    resource.display_name(),
                    e
                )
            })?;
        if result.continuation.is_some() {
            tracing::warn!(
                "{} returned more than the page limit; results are truncated",
                operation
            );
        }
        Ok(result.items)
    }

    /// Resource Graph query across every subscription the signed-in identity can read.
    /// Handles `$skipToken` continuation and returns the merged rows.
    pub async fn resource_graph(&self, query: &str) -> Result<Vec<Value>> {
        let mut rows = Vec::new();
        let mut skip: Option<String> = None;
        for _ in 0..100 {
            let mut options = json!({ "resultFormat": "objectArray", "$top": 1000 });
            if let Some(token) = &skip {
                options["$skipToken"] = Value::String(token.clone());
            }
            let body = self
                .call(
                    Resource::AzureResourceManager,
                    "azure.resource_graph.resources.post",
                    json!({ "parameters": {}, "body": { "query": query, "options": options } }),
                )
                .await?;
            if let Some(data) = body.get("data").and_then(|d| d.as_array()) {
                rows.extend(data.iter().cloned());
            }
            skip = body
                .get("$skipToken")
                .and_then(|t| t.as_str())
                .map(String::from);
            if skip.is_none() {
                break;
            }
        }
        Ok(rows)
    }

    /// Junction requires the selected API version as an explicit parameter; fill it from the catalogue
    /// when the caller didn't.
    fn with_api_version(&self, operation: &str, mut input: Value) -> Result<Value> {
        let op = self.executor.registry().resolve(operation, None, false)?;
        if let Some(version) = &op.api_version {
            if !input.is_object() {
                input = json!({});
            }
            let params = input
                .as_object_mut()
                .unwrap()
                .entry("parameters")
                .or_insert_with(|| json!({}));
            if let Some(map) = params.as_object_mut() {
                if op.parameters.iter().any(|p| p.name == "api-version") {
                    map.entry("api-version")
                        .or_insert(Value::String(version.clone()));
                }
            }
        }
        Ok(input)
    }

    async fn access_token(&self, resource: Resource, audience: &str) -> Result<AccessToken> {
        let info = self.auth.get_resource_token_info(resource).await?;
        let secret = Secret::new(info.access_token).context("token value rejected")?;
        Ok(AccessToken::new(
            secret,
            TokenMetadata {
                tenant: self.auth.tenant_id().to_string(),
                audience: audience.to_string(),
                expires_at: SystemTime::from(info.expires_at),
                scopes: info.scopes,
                roles: Vec::new(),
                account: None,
            },
        ))
    }
}

/// Endpoint and token audience for a resource in the configured cloud.
fn endpoint_for(cloud: CloudEnvironment, resource: Resource) -> Result<(String, String)> {
    let commercial = cloud == CloudEnvironment::Commercial;
    let (endpoint, audience) = match resource {
        Resource::AzureResourceManager => {
            if commercial {
                (
                    "https://management.azure.com",
                    "https://management.azure.com",
                )
            } else {
                (
                    "https://management.usgovcloudapi.net",
                    "https://management.usgovcloudapi.net",
                )
            }
        }
        Resource::DefenderForEndpoint => {
            if commercial {
                (
                    "https://api.securitycenter.microsoft.com",
                    "https://api.securitycenter.microsoft.com",
                )
            } else {
                (
                    "https://api-gcc.securitycenter.microsoft.us",
                    "https://api-gcc.securitycenter.microsoft.us",
                )
            }
        }
        Resource::PowerPlatform => (
            "https://api.powerplatform.com",
            "https://api.powerplatform.com",
        ),
        other => anyhow::bail!(
            "{} is not served through the Junction catalogue",
            other.display_name()
        ),
    };
    Ok((endpoint.to_string(), audience.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_catalogue_loads_and_lists_expected_operations() {
        let manifest: RegistryManifest = serde_json::from_str(CATALOG).unwrap();
        let registry = Registry::load(manifest).unwrap();
        for id in [
            "azure.resource_graph.resources.post",
            "defender.cloud.pricings.list",
            "sentinel.securityinsights.alert_rules.list",
            "defender.endpoint.machines.list",
        ] {
            registry
                .resolve(id, None, false)
                .unwrap_or_else(|e| panic!("{id}: {e}"));
        }
    }

    #[test]
    fn catalogue_matches_operations_list() {
        let listed: Vec<String> = include_str!("../controls/junction-operations.txt")
            .lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .map(String::from)
            .collect();
        let manifest: RegistryManifest = serde_json::from_str(CATALOG).unwrap();
        let mut embedded: Vec<String> = manifest.operations.iter().map(|o| o.id.clone()).collect();
        embedded.sort();
        embedded.dedup();
        let mut wanted = listed.clone();
        wanted.sort();
        assert_eq!(
            embedded, wanted,
            "run scripts/junction-catalog.py after editing controls/junction-operations.txt"
        );
    }

    #[test]
    fn params_builds_parameter_object() {
        let p = JunctionGateway::params(&[("subscriptionId", "abc")]);
        assert_eq!(p["parameters"]["subscriptionId"], "abc");
    }
}
